"""initial_migration

Revision ID: 8d4f97e4630a
Revises: fbff346a1207
Create Date: 2026-02-24 09:37:15.156729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4f97e4630a'
down_revision: Union[str, Sequence[str], None] = 'fbff346a1207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livros', sa.Column('qtd_total', sa.Integer(), nullable=True))
    op.add_column('livros', sa.Column('qtd_disponivel', sa.Integer(), nullable=True))
    op.alter_column('usuarios', 'senha',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'senha',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('livros', 'qtd_disponivel')
    op.drop_column('livros', 'qtd_total')
    # ### end Alembic commands ###
